(cl:defpackage ground_projection-srv
  (:use )
  (:export
   "ESTIMATEHOMOGRAPHY"
   "<ESTIMATEHOMOGRAPHY-REQUEST>"
   "ESTIMATEHOMOGRAPHY-REQUEST"
   "<ESTIMATEHOMOGRAPHY-RESPONSE>"
   "ESTIMATEHOMOGRAPHY-RESPONSE"
   "GETGROUNDCOORD"
   "<GETGROUNDCOORD-REQUEST>"
   "GETGROUNDCOORD-REQUEST"
   "<GETGROUNDCOORD-RESPONSE>"
   "GETGROUNDCOORD-RESPONSE"
   "GETIMAGECOORD"
   "<GETIMAGECOORD-REQUEST>"
   "GETIMAGECOORD-REQUEST"
   "<GETIMAGECOORD-RESPONSE>"
   "GETIMAGECOORD-RESPONSE"
  ))

