# Notes
#
# Use explicit "links" for connections to images.
#
# Use "depends_on" so that everything will stop if a container exits.

version: '3'
services:
  ros_core:
    image: ros:noetic-ros-core
    command: roscore
    environment:
      ROS_MASTER_URI: "http://ros_core:11311"
    networks: &networks
    - duckietown-docker-net
    env_file: &env_file
    - setup/parameters.env
    expose:
    - "11311"
    ports:
    - "11311:11311"

  ros_template:
      image: ${AIDO_REGISTRY}/duckietown/challenge-aido_lf-template-ros:daffy-amd64
      environment:
        AIDONODE_DATA_IN: /fifos/agent-in
        AIDONODE_DATA_OUT: fifo:/fifos/agent-out
        ROS_MASTER_URI: "http://ros_core:11311"
        HOSTNAME: "default"
        VEHICLE_NAME: "default"
      volumes: &fifos
        - fifos:/fifos
      networks: *networks
      links:
        - ros_core
      depends_on:
        - ros_core
        - middleware_manager

  novnc:
      image: duckietown/docker-ros-vnc:daffy
      networks: *networks
      env_file: *env_file
      environment:
        ROS_MASTER_URI: "http://ros_core:11311"
        HOSTNAME: "default"
        VEHICLE_NAME: "default"
      expose:
      - "5901"
      - "6901"
      ports:
      - "5901:5901"
      - "6901:6901"
      links:
        - ros_core
      depends_on:
        - ros_core

  simulator:
      image: ${AIDO_REGISTRY}/duckietown/challenge-aido_lf-simulator-gym:daffy
      env_file: *env_file
      environment:
        AIDONODE_DATA_IN: /fifos/simulator-in
        AIDONODE_DATA_OUT: fifo:/fifos/simulator-out
        AIDONODE_CONFIG: |
          env_constructor: Simulator
          env_parameters:
            max_steps: 500001 # we don't want the gym to reset itself
            camera_width: 640
            camera_height: 480
            #camera_width: 320
            #camera_height: 240
      volumes: *fifos
      networks: *networks
      depends_on:
        - middleware_manager

  middleware_manager:
      image: ${AIDO_REGISTRY}/duckietown/mooc-fifos-connector:daffy
      environment:
        middleware_parameters: |
          episodes_per_scenario: 1
          episode_length_s: 100.0
          min_episode_length_s: 1.0
          seed: 42
          physics_dt: 0.05
          max_failures: 2
          agent_in: /fifos/agent-in
          agent_out: /fifos/agent-out
          sim_in: /fifos/simulator-in
          sim_out: /fifos/simulator-out
          sm_in: None
          sm_out: None
          timeout_initialization: 15
          timeout_regular: 360
      volumes: *fifos
      networks: *networks
      env_file: *env_file

volumes:
  fifos:

networks:
    duckietown-docker-net:
