# Notes
#
# Use explicit "links" for connections to images.
#
# Use "depends_on" so that everything will stop if a container exits.

version: '3'
services:
  ros_core:
      image: ros:noetic-ros-core
      command: roscore
      environment:
        ROS_MASTER_URI: "http://ros_core:11311"
      networks: &networks
      - duckietown-docker-net
      env_file: &env_file
      - setup/parameters.env
        #expose:
        #- "11311"
      ports:
      - "11311:11311"

  duckiebot_bridge:
    image: duckietown/dt-duckiebot-fifos-bridge:daffy-amd64
    environment:
      HOSTNAME: "udem02"
      VEHICLE_NAME: "udem02"
      ROS_MASTER_URI: "http://192.168.0.169:11311"
    volumes:
        - fifos:/fifos
    network_mode: host


  ros_template:
      image: ${AIDO_REGISTRY}/duckietown/challenge-aido_lf-template-ros:daffy-amd64
      command: |
        bash -c "\
        catkin build --workspace /code/overlay_ws &&\
        source /code/overlay_ws/devel/setup.bash &&\
        roslaunch --wait duckietown_demos lane_following.launch & python3 solution.py"
      environment:
        AIDONODE_DATA_IN: /fifos/agent-in
        AIDONODE_DATA_OUT: fifo:/fifos/agent-out
        ROS_MASTER_URI: "http://ros_core:11311"
        ROS_HOSTNAME: ""
        HOSTNAME: "default"
        VEHICLE_NAME: "default"
      volumes:
        - fifos:/fifos
        - ./setup/assets:/data/config
        - ./overlay_ws:/code/overlay_ws
      networks: *networks
        #      links:
        #        - ros_core
      depends_on:
        - ros_core
        - duckiebot_bridge

  novnc:
      image: duckietown/dt-gui-tools:daffy-amd64
      command: dt-launcher-vnc
      networks: *networks
      env_file: *env_file
      environment:
        ROS_MASTER_URI: "http://ros_core:11311"
        HOSTNAME: default
        VEHICLE_NAME: default
      ports:
      - "8087:8087"
      depends_on:
      - ros_core

  car_interface:
      image: duckietown/dt-car-interface:daffy-amd64
      environment:
        ROS_MASTER_URI: "http://ros_core:11311"
        VEHICLE_NAME: default
      networks: *networks

volumes:
  fifos:

networks:
    duckietown-docker-net:
