# Exercise configuration file

agent_base: "rpl_ros_baseline" # currently not implemented, the agent base image to use
ws_dir: "exercise_ws" # directory that contains the code
agent_run_cmd: "run_all.sh" # the script in "launchers" to run the agent with

  
