// Generated by gencpp from file ground_projection/GetGroundCoord.msg
// DO NOT EDIT!


#ifndef GROUND_PROJECTION_MESSAGE_GETGROUNDCOORD_H
#define GROUND_PROJECTION_MESSAGE_GETGROUNDCOORD_H

#include <ros/service_traits.h>


#include <ground_projection/GetGroundCoordRequest.h>
#include <ground_projection/GetGroundCoordResponse.h>


namespace ground_projection
{

struct GetGroundCoord
{

typedef GetGroundCoordRequest Request;
typedef GetGroundCoordResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetGroundCoord
} // namespace ground_projection


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ground_projection::GetGroundCoord > {
  static const char* value()
  {
    return "4a593ebeb349392dda67c9ac9b35b490";
  }

  static const char* value(const ::ground_projection::GetGroundCoord&) { return value(); }
};

template<>
struct DataType< ::ground_projection::GetGroundCoord > {
  static const char* value()
  {
    return "ground_projection/GetGroundCoord";
  }

  static const char* value(const ::ground_projection::GetGroundCoord&) { return value(); }
};


// service_traits::MD5Sum< ::ground_projection::GetGroundCoordRequest> should match
// service_traits::MD5Sum< ::ground_projection::GetGroundCoord >
template<>
struct MD5Sum< ::ground_projection::GetGroundCoordRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ground_projection::GetGroundCoord >::value();
  }
  static const char* value(const ::ground_projection::GetGroundCoordRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_projection::GetGroundCoordRequest> should match
// service_traits::DataType< ::ground_projection::GetGroundCoord >
template<>
struct DataType< ::ground_projection::GetGroundCoordRequest>
{
  static const char* value()
  {
    return DataType< ::ground_projection::GetGroundCoord >::value();
  }
  static const char* value(const ::ground_projection::GetGroundCoordRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ground_projection::GetGroundCoordResponse> should match
// service_traits::MD5Sum< ::ground_projection::GetGroundCoord >
template<>
struct MD5Sum< ::ground_projection::GetGroundCoordResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ground_projection::GetGroundCoord >::value();
  }
  static const char* value(const ::ground_projection::GetGroundCoordResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ground_projection::GetGroundCoordResponse> should match
// service_traits::DataType< ::ground_projection::GetGroundCoord >
template<>
struct DataType< ::ground_projection::GetGroundCoordResponse>
{
  static const char* value()
  {
    return DataType< ::ground_projection::GetGroundCoord >::value();
  }
  static const char* value(const ::ground_projection::GetGroundCoordResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GROUND_PROJECTION_MESSAGE_GETGROUNDCOORD_H
