// Generated by gencpp from file ground_projection/GetGroundCoordRequest.msg
// DO NOT EDIT!


#ifndef GROUND_PROJECTION_MESSAGE_GETGROUNDCOORDREQUEST_H
#define GROUND_PROJECTION_MESSAGE_GETGROUNDCOORDREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <duckietown_msgs/Pixel.h>

namespace ground_projection
{
template <class ContainerAllocator>
struct GetGroundCoordRequest_
{
  typedef GetGroundCoordRequest_<ContainerAllocator> Type;

  GetGroundCoordRequest_()
    : uv()  {
    }
  GetGroundCoordRequest_(const ContainerAllocator& _alloc)
    : uv(_alloc)  {
  (void)_alloc;
    }



   typedef  ::duckietown_msgs::Pixel_<ContainerAllocator>  _uv_type;
  _uv_type uv;





  typedef boost::shared_ptr< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetGroundCoordRequest_

typedef ::ground_projection::GetGroundCoordRequest_<std::allocator<void> > GetGroundCoordRequest;

typedef boost::shared_ptr< ::ground_projection::GetGroundCoordRequest > GetGroundCoordRequestPtr;
typedef boost::shared_ptr< ::ground_projection::GetGroundCoordRequest const> GetGroundCoordRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator1> & lhs, const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator2> & rhs)
{
  return lhs.uv == rhs.uv;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator1> & lhs, const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_projection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fba398636bea4394b5da7cf9599a6d3c";
  }

  static const char* value(const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfba398636bea4394ULL;
  static const uint64_t static_value2 = 0xb5da7cf9599a6d3cULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_projection/GetGroundCoordRequest";
  }

  static const char* value(const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"duckietown_msgs/Pixel uv\n"
"\n"
"\n"
"================================================================================\n"
"MSG: duckietown_msgs/Pixel\n"
"int32 u\n"
"int32 v\n"
;
  }

  static const char* value(const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uv);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetGroundCoordRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_projection::GetGroundCoordRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_projection::GetGroundCoordRequest_<ContainerAllocator>& v)
  {
    s << indent << "uv: ";
    s << std::endl;
    Printer< ::duckietown_msgs::Pixel_<ContainerAllocator> >::stream(s, indent + "  ", v.uv);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_PROJECTION_MESSAGE_GETGROUNDCOORDREQUEST_H
