// Generated by gencpp from file ground_projection/GetImageCoordResponse.msg
// DO NOT EDIT!


#ifndef GROUND_PROJECTION_MESSAGE_GETIMAGECOORDRESPONSE_H
#define GROUND_PROJECTION_MESSAGE_GETIMAGECOORDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <duckietown_msgs/Vector2D.h>

namespace ground_projection
{
template <class ContainerAllocator>
struct GetImageCoordResponse_
{
  typedef GetImageCoordResponse_<ContainerAllocator> Type;

  GetImageCoordResponse_()
    : normalized_uv()  {
    }
  GetImageCoordResponse_(const ContainerAllocator& _alloc)
    : normalized_uv(_alloc)  {
  (void)_alloc;
    }



   typedef  ::duckietown_msgs::Vector2D_<ContainerAllocator>  _normalized_uv_type;
  _normalized_uv_type normalized_uv;





  typedef boost::shared_ptr< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetImageCoordResponse_

typedef ::ground_projection::GetImageCoordResponse_<std::allocator<void> > GetImageCoordResponse;

typedef boost::shared_ptr< ::ground_projection::GetImageCoordResponse > GetImageCoordResponsePtr;
typedef boost::shared_ptr< ::ground_projection::GetImageCoordResponse const> GetImageCoordResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ground_projection::GetImageCoordResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ground_projection::GetImageCoordResponse_<ContainerAllocator1> & lhs, const ::ground_projection::GetImageCoordResponse_<ContainerAllocator2> & rhs)
{
  return lhs.normalized_uv == rhs.normalized_uv;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ground_projection::GetImageCoordResponse_<ContainerAllocator1> & lhs, const ::ground_projection::GetImageCoordResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ground_projection

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e079b9787496ba75117334836e96c45";
  }

  static const char* value(const ::ground_projection::GetImageCoordResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e079b9787496ba7ULL;
  static const uint64_t static_value2 = 0x5117334836e96c45ULL;
};

template<class ContainerAllocator>
struct DataType< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ground_projection/GetImageCoordResponse";
  }

  static const char* value(const ::ground_projection::GetImageCoordResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
"\n"
"duckietown_msgs/Vector2D normalized_uv\n"
"\n"
"================================================================================\n"
"MSG: duckietown_msgs/Vector2D\n"
"float32 x\n"
"float32 y\n"
;
  }

  static const char* value(const ::ground_projection::GetImageCoordResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.normalized_uv);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetImageCoordResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ground_projection::GetImageCoordResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ground_projection::GetImageCoordResponse_<ContainerAllocator>& v)
  {
    s << indent << "normalized_uv: ";
    s << std::endl;
    Printer< ::duckietown_msgs::Vector2D_<ContainerAllocator> >::stream(s, indent + "  ", v.normalized_uv);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GROUND_PROJECTION_MESSAGE_GETIMAGECOORDRESPONSE_H
