#lane_control/lane_controller_node

min_r: 0.0001
max_r: 0.03
dt_path: 0.1
max_dist_fact: 1.4
min_dist: 0.04      # Minimum distance error to correct
min_angle: 0.2      # Minimum angle error to correct
num_dt: 5           # Number of time steps to split up a rotation only turn
homog_tol: 0.02
plan_min_exec_time: 0.1

# Define input gains
k_v: 3.0
k_omega: 0.9