#lane_control/lane_controller_node

min_r: 0.01 
max_r: 0.03
dt_path: 0.01
max_dist_fact: 1.2
min_dist: 0.1      # Minimum distance error to correct
min_angle: 0.2      # Minimum angle error to correct
num_dt: 5           # Number of time steps to split up a rotation only turn


# Define input gains
k_v: 30.0
k_omega: 1.0