version: '3'
services:
  middleware_manager:
    #image: courchesnea/dt-middleware:test
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      middleware_parameters: |
        episodes_per_scenario: 1
        episode_length_s: 100.0
        min_episode_length_s: 1.0
        seed: 42
        physics_dt: 0.05
        max_failures: 2
        agent_in: /fifos/agent-in
        agent_out: /fifos/agent-out
        sim_in: /fifos/simulator-in
        sim_out: /fifos/simulator-out
        sm_in: None
        sm_out: None
        timeout_initialization: 15
        timeout_regular: 30
    volumes: &volumes
      - ./challenges-dir:/challenges
      - fifos:/fifos

  simulator:
    image: duckietown/challenge-aido_lf-simulator-gym:daffy-aido4
    #image: courchesnea/dt-simbridge:test
    environment:
      AIDONODE_DATA_IN: /fifos/simulator-in
      AIDONODE_DATA_OUT: fifo:/fifos/simulator-out
    volumes: *volumes

volumes:
  fifos:
