version: '3'
services:
    lanefollow:
        image: duckietown/dt-notebook:udem
        build:
            context: .
            dockerfile: DockerfileNB
        working_dir: /duckietown
        networks:
        - duckietown-docker-net
        depends_on:
        - "sim"
        volumes:
        - ./catkin_ws:/duckietown/catkin_ws
        - ./notebooks:/duckietown/notebooks
        - ./utils:/duckietown/utils
        - ./custom:/duckietown/custom
        - ./custom_ws:/duckietown/custom_ws
        - ./simulation:/duckietown/simulation
        - /tmp/.X11-unix:/tmp/.X11-unix
        environment:
        - "ROS_MASTER_URI=http://sim:11311"
        - "HOSTNAME=default"
        - "VEHICLE_NAME=default"
        - "DISPLAY=:99"
        expose:
        - "8888"
        ports:
        - "8888:8888"

    novnc:
        image: duckietown/dt-novnc:udem
        build:
            context: .
            dockerfile: DockerfileNoVNC
        networks:
        - duckietown-docker-net
        environment:
        - "ROS_MASTER_URI=http://sim:11311"
        - "HOSTNAME=default"
        - "VEHICLE_NAME=default"
        expose:
        - "5901"
        - "6901"
        ports:
        - "5901:5901"
        - "6901:6901"

    sim:
        image: duckietown/dt-sim:udem
        build:
            context: .
            dockerfile: DockerfileSim
        networks:
        - duckietown-docker-net
        volumes:
        - ./simulation:/duckietown/simulation
        - ./utils:/duckietown/utils        
        environment:
        - "ROS_MASTER_URI=http://sim:11311"
        - "HOSTNAME=default"
        - "VEHICLE_NAME=default"
        - "DISPLAY=:99"

networks:
    duckietown-docker-net: