// Generated by gencpp from file duckietown_msgs/AntiInstagramTransform_CB.msg
// DO NOT EDIT!


#ifndef DUCKIETOWN_MSGS_MESSAGE_ANTIINSTAGRAMTRANSFORM_CB_H
#define DUCKIETOWN_MSGS_MESSAGE_ANTIINSTAGRAMTRANSFORM_CB_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace duckietown_msgs
{
template <class ContainerAllocator>
struct AntiInstagramTransform_CB_
{
  typedef AntiInstagramTransform_CB_<ContainerAllocator> Type;

  AntiInstagramTransform_CB_()
    : header()
    , th()  {
      th.assign(0);
  }
  AntiInstagramTransform_CB_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , th()  {
  (void)_alloc;
      th.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<int16_t, 6>  _th_type;
  _th_type th;





  typedef boost::shared_ptr< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> const> ConstPtr;

}; // struct AntiInstagramTransform_CB_

typedef ::duckietown_msgs::AntiInstagramTransform_CB_<std::allocator<void> > AntiInstagramTransform_CB;

typedef boost::shared_ptr< ::duckietown_msgs::AntiInstagramTransform_CB > AntiInstagramTransform_CBPtr;
typedef boost::shared_ptr< ::duckietown_msgs::AntiInstagramTransform_CB const> AntiInstagramTransform_CBConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator1> & lhs, const ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.th == rhs.th;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator1> & lhs, const ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace duckietown_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ad95a08e9897d117b5fa255272552409";
  }

  static const char* value(const ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xad95a08e9897d117ULL;
  static const uint64_t static_value2 = 0xb5fa255272552409ULL;
};

template<class ContainerAllocator>
struct DataType< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "duckietown_msgs/AntiInstagramTransform_CB";
  }

  static const char* value(const ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int16[6] th\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.th);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AntiInstagramTransform_CB_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::duckietown_msgs::AntiInstagramTransform_CB_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "th[]" << std::endl;
    for (size_t i = 0; i < v.th.size(); ++i)
    {
      s << indent << "  th[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.th[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DUCKIETOWN_MSGS_MESSAGE_ANTIINSTAGRAMTRANSFORM_CB_H
