ARG REPO_NAME="dt-ros-commons"

ARG ARCH=amd64
ARG MAJOR=daffy
ARG ROS_DISTRO=kinetic
ARG BASE_TAG=${MAJOR}-${ARCH}


# define base image
FROM duckietown/dt-ros-${ROS_DISTRO}-base:${BASE_TAG}

ENV SOURCE_DIR /code
ENV CATKIN_WS_DIR "${SOURCE_DIR}/catkin_ws"
ARG REPO_PATH="${CATKIN_WS_DIR}/src/${REPO_NAME}"

# copy dependencies files only
COPY ./dependencies-apt.txt /
COPY ./dependencies-py.txt /

# install apt dependencies
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    $(awk -F: '/^[^#]/ { print $1 }' /dependencies-apt.txt | uniq) \
  && rm -rf /var/lib/apt/lists/*

# install python dependencies
RUN pip install -r /dependencies-py.txt

# install sphynx and related packages
RUN pip install sphinx==1.7.0 sphinx-rtd-theme sphinx-autobuild mock
RUN cd /; git clone https://github.com/AleksandarPetrov/napoleon; cd /napoleon; python setup.py install -f

# copy the source and docs files
COPY packages "${CATKIN_WS_DIR}/src/${repo_name}"
COPY docs "${CATKIN_WS_DIR}/src/${repo_name}"

# build packages
RUN source /opt/ros/${ROS_DISTRO}/setup.sh && \
  catkin_make -C ${CATKIN_WS_DIR}/

CMD [bash -c 'source "${CATKIN_WS_DIR}/devel/setup.bash"; cd "${CATKIN_WS_DIR}/src/${repo_name}/docs"; make html']
